services:

  resident-db: &database
    image: postgres:latest
    container_name: resident_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  user-db:
    <<: *database
    container_name: user_db
    ports:
      - 5433:5432


networks:
  eureka-network:
    driver: bridge