services:

  resident-db: &database
    image: postgres:latest
    container_name: resident_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  user-db:
    <<: *database
    container_name: user_db
    ports:
      - 5433:5432

  employee-db:
    <<: *database
    container_name: employee_db
    ports:
      - 5434:5432

  delivery-db:
    <<: *database
    container_name: delivery_db
    ports:
      - 5435:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

networks:
  eureka-network:
    driver: bridge