services:

  resident-db: &database
    image: postgres:latest
    container_name: resident_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  user-db:
    <<: *database
    container_name: user_db
    ports:
      - 5433:5432

  employee-db:
    <<: *database
    container_name: employee_db
    ports:
      - 5434:5432

  delivery-db:
    <<: *database
    container_name: delivery_db
    ports:
      - 5435:5432

  eureka-service:
    build: ./eureka
    container_name: eureka_service
    ports:
      - 8761:8761

  resident-api:
    build: ./resident
    container_name: resident_api
    ports:
      - 8081:8081
    environment:
      EUREKA_SERVICE: http://eureka-service:8761/eureka
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://resident-db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
    depends_on:
      - resident-db
      - eureka-service

  employee-api:
    build: ./employee
    container_name: employee_api
    ports:
      - 8082:8082
    environment:
      EUREKA_SERVICE: http://eureka-service:8761/eureka
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://employee-db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
    depends_on:
      - employee-db
      - eureka-service

  user-api:
    build: ./user
    container_name: user_api
    ports:
      - 8083:8083
    environment:
      EUREKA_SERVICE: http://eureka-service:8761/eureka
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      RESIDENT_URL: http://resident-api:8081/api/resident
      EMPLOYEE_URL: http://employee-api:8082/api/employee
    depends_on:
      - user-db
      - eureka-service
      - resident-api
      - employee-api

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

networks:
  eureka-network:
    driver: bridge