spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authenticate
          uri: lb://USER-API
          predicates:
            - Path=/api/login
        - id: validate
          uri: lb://USER-API
          predicates:
            - Path=/api/login/validate
        - id: create-users
          uri: lb://USER-API
          predicates:
            - Path=/api/user/**
        - id: user-swagger
          uri: lb://USER-API
          predicates:
            - Path=/user-api/v3/api-docs
          filters:
            - StripPrefix=1

        - id: resident_create
          uri: lb://RESIDENT-API
          predicates:
            - Path=/api/resident/**
            - Method=GET,POST

        - id: resident_other_operations
          uri: lb://RESIDENT-API
          predicates:
            - Path=/api/resident/**
            - Method=PUT,DELETE
          filters:
            - AuthenticatorFilter=RESIDENT

        - id: create_employee
          uri: lb://EMPLOYEE-API
          predicates:
            - Path=/api/employee/**
            - Method=GET,POST



        - id: resident-swagger
          uri: lb://RESIDENT-API
          predicates:
            - Path=/resident-api/v3/api-docs
          filters:
            - StripPrefix=1

        - id: employee_other_operations
          uri: lb://EMPLOYEE-API
          predicates:
            - Path=/api/employee/**
            - Method=PUT,DELETE
          filters:
            - AuthenticatorFilter=EMPLOYEE

        - id: employee-swagger
          uri: lb://EMPLOYEE-API
          predicates:
            - Path=/employee-api/v3/api-docs
          filters:
            - StripPrefix=1

        - id: register_delivery
          uri: lb://DELIVERY-API
          predicates:
            - Path=/api/delivery/register
            - Method=POST

        - id: delivery_get
          uri: lb://DELIVERY-API
          predicates:
            - Path=/api/delivery/**
            - Method=GET

    discovery:
      locator:
        lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

login:
  api: ${LOGIN_API}


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-api/v3/api-docs
        name: User API Service
        primaryName: User API Service
      - url: /resident-api/v3/api-docs
        name: Resident API Service
        primaryName: Resident API Service
      - url: /employee-api/v3/api-docs
        name: Employee API Service
        primaryName: Employee API Service
