spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: create-users
          uri: lb://USER-API
          predicates:
            - Path=/api/user/**
            - Method=POST

        - id: authenticate
          uri: lb://USER-API
          predicates:
            - Path=/api/login

        - id: validate
          uri: lb://USER-API
          predicates:
            - Path=/api/login/validate

        - id: resident-api
          uri: lb://RESIDENT-API
          predicates:
            - Path=/api/resident/**
          filters:
            - AuthenticatorFilter=RESIDENT,EMPLOYEE

        - id: employee-api
          uri: lb://EMPLOYEE-API
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthenticatorFilter=EMPLOYEE

        - id: register-delivery
          uri: lb://DELIVERY-API
          predicates:
            - Path=/api/delivery/register
            - Method=POST
          filters:
            - AuthenticatorFilter=EMPLOYEE

        - id: delivered-package
          uri: lb://DELIVERY-API
          predicates:
            - Path=/api/delivery/{id}/delivered
            - Method=PUT
          filters:
            - AuthenticatorFilter=EMPLOYEE

        - id: read-notification
          uri: lb://DELIVERY-API
          predicates:
            - Path=/api/delivery/{id}/notification/read
            - Method=PUT
          filters:
            - AuthenticatorFilter=RESIDENT

        - id: delivery-get
          uri: lb://DELIVERY-API
          predicates:
            - Path=/api/delivery/**
            - Method=GET
          filters:
            - AuthenticatorFilter=EMPLOYEE,RESIDENT


        - id: user-swagger
          uri: lb://USER-API
          predicates:
            - Path=/user-api/v3/api-docs
          filters:
            - StripPrefix=1

        - id: resident-swagger
          uri: lb://RESIDENT-API
          predicates:
            - Path=/resident-api/v3/api-docs
          filters:
            - StripPrefix=1



        - id: employee-swagger
          uri: lb://EMPLOYEE-API
          predicates:
            - Path=/employee-api/v3/api-docs
          filters:
            - StripPrefix=1

        - id: delivery-swagger
          uri: lb://DELIVERY-API
          predicates:
            - Path=/delivery-api/v3/api-docs
          filters:
            - StripPrefix=1

    discovery:
      locator:
        lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

login:
  api: ${LOGIN_API}


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-api/v3/api-docs
        name: User API Service
        primaryName: User API Service
      - url: /resident-api/v3/api-docs
        name: Resident API Service
        primaryName: Resident API Service
      - url: /employee-api/v3/api-docs
        name: Employee API Service
        primaryName: Employee API Service
      - url: /delivery-api/v3/api-docs
        name: Delivery API Service
        primaryName: Delivery API Service
