spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: resident_auth
          uri: lb://USER-API
          predicates:
            - Path=/api/login/resident
        - id: validate
          uri: lb://USER-API
          predicates:
            - Path=/api/login/validate
        - id: create_users
          uri: lb://USER-API
          predicates:
            - Path=/api/user/**
        - id: create_resident
          uri: lb://RESIDENT-API
          predicates:
            - Path=/api/resident
            - Method=POST
        - id: get_resident
          uri: lb://RESIDENT-API
          predicates:
            - Path=/api/resident/**
            - Method=GET
        - id: cliente
          uri: lb://CUSTOMER-API
          predicates:
            - Path=/api/cliente/**
          filters:
            - AuthenticatorFilter
        - id: cartao
          uri: lb://CREDITCARD-API
          predicates:
            - Path=/api/cartao/**
          filters:
            - AuthenticatorFilter
        - id: pagamento
          uri: lb://PAYMENT-API
          predicates:
            - Path=/api/pagamentos/**
          filters:
            - AuthenticatorFilter
        - id: login-swagger
          uri: lb://LOGIN-API
          predicates:
            - Path=/login-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: cliente-swagger
          uri: lb://CUSTOMER-API
          predicates:
            - Path=/customer-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: cartao-swagger
          uri: lb://CREDITCARD-API
          predicates:
            - Path=/credit-card-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: pagamento-swagger
          uri: lb://PAYMENT-API
          predicates:
            - Path=/payment-api/v3/api-docs
          filters:
            - StripPrefix=1

    discovery:
      locator:
        lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

login:
  api: ${LOGIN_API}


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /login-api/v3/api-docs
        name: Login API Service
        primaryName: Login API Service
      - url: /customer-api/v3/api-docs
        name: Customer API Service
        primaryName: Customer API Service
      - url: /credit-card-api/v3/api-docs
        name: Credit Card API Service
        primaryName: Credit Card API Service
      - url: /payment-api/v3/api-docs
        name: Payment API Service
        primaryName: Payment API Service