spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  application:
    name: DELIVERY-API
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true





resident:
  url: ${RESIDENT_URL}
employee:
  url: ${EMPLOYEE_URL}

rabbitmq:
  queue:
    name: ${RABBITMQ_QUEUE_NAME}
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME}
    routingKey: ${RABBITMQ_ROUTING_KEY}

openapi:
  service:
    title: DELIVERY-API Doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  swagger-ui:
    path: /delivery-api/swagger-ui.html
  api-docs:
    path: /delivery-api/v3/api-docs