spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  application:
    name: EMPLOYEE-API
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true

openapi:
  service:
    title: EMPLOYEE-API Doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  swagger-ui:
    path: /employee-api/swagger-ui.html
  api-docs:
    path: /employee-api/v3/api-docs